
files.extend-exclude = ["npins/sources.json"]
default.extend-ignore-words-re = [
  "(?i)(noice)",
  "befores",
  "annote",
  "viw",
  "typ",
  "edn",
  "esy",
  "BA", # somehow "BANanaD3V" is valid, but BA is not...
]

